### ISSUE TITLE
List of transfers TO a partyId not correctly returned by transfers gRPC method

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/data-node#459] opened 2022-03-21 12:37 UTC
# Problem encountered
There is a transfers gRPC method for retrieving the list of transfers and takes in a partyID aka public key and is_to / is_from as input parameters and returns the list of transfers matching the criteria

This works perfectly fine if we provide a partyId and is_from=True as parameters and the method returns the list of transfers **FROM** that partyId

However , if we provide a partyId and is_to=True as parameters , then the list of transfers IS NOT returned even though transfers **TO** that partyId exist

# Observed behaviour
The correct list of transfers is NOT returned by the transfers gRPC method if is_to=True and a valid partyId is provided as input.

# Expected behaviour
Correct list of transfers should be returned by the transfers gRPC method

# System response

Transfers FROM:
{'transfers': [{'id': '19627db02e67e0de0c7a48bda96391bbce82670e56c678c36b33a4873df4089c', 'from': '2e771ce53a9deaa5841cd917bf807e7ef26309b58c0d337bb3880320ff40f404', 'fromAccountType': 'ACCOUNT_TYPE_GENERAL', 'to': '72ddab9c10b8ab763090b5a019b3240d0300d31b583fddb5a0d276e0067785e6', 'toAccountType': 'ACCOUNT_TYPE_GENERAL', 'asset': '797904fa6f5c85904c005ed3a792127e49d94f5011e33a3c55f498ced4b6137a', 'amount': '2456', 'reference': 'TestTransfer', 'status': 'STATUS_DONE', 'timestamp': '1647865057395896228'}]}

Transfers TO:
Transfer List TO is {'transfers': [{'id': '', 'from': '', 'fromAccountType': 'ACCOUNT_TYPE_UNSPECIFIED', 'to': '', 'toAccountType': 'ACCOUNT_TYPE_UNSPECIFIED', 'asset': '', 'amount': '', 'reference': '', 'status': 'STATUS_UNSPECIFIED', 'timestamp': '0'}]}

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:
1. Perform a wallet to wallet transfer
2. Call transfers gRPC method with the correct TO account partyId and is_to=True parameters
3. No transfers are returned by the method

# Evidence

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

**Comment by gordsport** [comment] 2022-07-29 14:38
duplicate of:
- https://github.com/vegaprotocol/vega/issues/5703

**Closed by gordsport** 2022-07-29 14:38 UTC
Labels: Low, api, bug
