### ISSUE TITLE
Data node v2 query enhancements for HistoricBalances

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/data-node#642] opened 2022-05-31 19:06 UTC
Ref: https://github.com/vegaprotocol/protos/blob/develop/sources/data-node/api/v2/trading_data.proto

> @pscott31: This is the grpc API, and is used by a handful of new graphql calls like HistoricBalances and the various paged variants for fetching orders and trades. We haven't added anything for transfers yet, but this should be pretty straightforward to do. Is there something specific you want to to query? I'll make sure it's included if you can give me some good examples

> @cdm: May I request optional filters such as:
'time window' - from / to
'pagination' - either cursor or offset
A typical scenario for incentives could be Give me party X balance at startTimestamp and then again at endTimestamp
We often need to see how much gain or profit/loss in a set of assets for a party between two dates to rank them accurately for an incentive. This kind of audit history is key to not having to do hack/work around on our side, especially after checkpoint/snapshot is enabled

 Additionally are you soon going to add paginated deposits & withdrawals to the v2 API?

**Comment by gordsport** [comment] 2022-07-29 14:28
Closing as a duplicate of scheduled work

**Closed by gordsport** 2022-07-29 14:28 UTC
