### ISSUE TITLE
Deposits GraphQL query fails with "message": "The string did not match the expected pattern."

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/data-node#821] opened 2022-07-19 20:06 UTC
On Fairground testnet, the following GraphQL query doesnt return a list of deposits as expected/as it did before:

```
query {
    parties {
      id
      deposits{
        id
        asset { 
          id
          name
          decimals 
          symbol 
        }
        status
        createdTimestamp
        creditedTimestamp
        amount
      }
    }
  }
```

It returns an error as follows, when previously it returns the deposits for all parties:

```
{
  "errors": {
    "message": "The string did not match the expected pattern.",
    "stack": ""
  }
}
```

Sadly we need deposits for XYZgamma in order to work out top 25 %PNL and bottom 25 %PNL. This means the leaderboards are not updating so no one can be scored / ranked to win any prizes in the current implementation of the leaderboards.

If we write the same query but for accounts, it returns them all very quickly:

```
query {
    parties {
      id
      accounts(asset: "XYZgamma"){
        asset {
          id
          symbol
        }
        balance
        type
      }
      # deposits{
      #   id
      #   asset { 
      #     id
      #     name
      #     decimals 
      #     symbol 
      #   }
      #   status
      #   createdTimestamp
      #   creditedTimestamp
      #   amount
      # }
    }
  }
```

<img width="1440" alt="Screenshot 2022-07-19 at 20 41 38" src="https://user-images.githubusercontent.com/149245/179837845-f4227df0-81f4-46b3-a1ac-57ab90e5d8cb.png">

However if you combine the two portions of the query (or any other queries alongside the deposit query) it still returns the error `"message": "The string did not match the expected pattern."`

<img width="1436" alt="Screenshot 2022-07-19 at 20 41 08" src="https://user-images.githubusercontent.com/149245/179838838-903891f9-b9fd-4f8e-b469-10d27aa4916a.png">

Is it a PostgreSQL issues? We didn't see this behaviour with the badger backed stores.

**Comment by gordsport** [comment] 2022-07-20 08:45
Hey @cdm 
running this in [devnet](http://n04.d.vega.xyz:3008/playground) and it looks to return results as expected (albeit a little slow).

Is this blocking an incentive?

**Comment by daunatv** [comment] 2022-07-25 06:19
@gordsport we did run the incentive with the assumption of amounts but it was not optimal.

**Comment by gordsport** [comment] 2022-07-25 08:23
Thanks @daunatv - This will be resolved when the version from devnet is promoted through the stag/testnet

**Comment by guoguojin** [comment] 2022-07-26 09:21
I've just tried to reproduce this bug with the develop branch of Data Node and I cannot reproduce it. All queries specified in the ticket has returned results, I can look into again if the stag/test net is updated and the problem still persists.

**Comment by gordsport** [comment] 2022-07-29 14:08
CLosing as cant reproduce

**Closed as completed by gordsport** 2022-07-29 14:08 UTC
Labels: Critical, api, bug
